/* eslint-disable react/prop-types */
import { default as tuxedoXml } from "./js_svg/tuxedo";
import { default as karateXml } from "./js_svg/karate";
import { default as dancerXml } from "./js_svg/dancer";
//import { default as prisonerXml } from "./js_svg/prisoner";
import { default as hockeyXml } from "./js_svg/hockey";
import { default as pionerXml } from "./js_svg/pioner";
import { default as orangeXml } from "./js_svg/orange";
import { default as kgbXml } from "./js_svg/kgb";
import { default as babushkaXml } from "./js_svg/babushka";
import { default as bearXml } from "./js_svg/bear";
import { default as chickenXml } from "./js_svg/chicken";

const Resources = {
  head: [
    require("../assets/costumes/head_tb_1000_ps.png"),
    require("../assets/costumes/head_tb_1000_ps_300_01.png"),
  ],
  chicken: [
    require("../assets/costumes/chicken0.png"),
    require("../assets/costumes/chicken1.png"),
  ],
  heart: require("../assets/other/heart.png"),
  heroLight: require("../assets/other/hero_light.png"),
  shareButton: require("../assets/other/share_button.png"),
  images: {
    "costumes/tuxedo/body_trimmed.png": require("../assets/costumes/tuxedo/body_trimmed.png"),
    "costumes/tuxedo/left_hand_trimmed.png": require("../assets/costumes/tuxedo/left_hand_trimmed.png"),
    "costumes/tuxedo/right_hand_trimmed.png": require("../assets/costumes/tuxedo/right_hand_trimmed.png"),
    "costumes/tuxedo/left_leg_trimmed.png": require("../assets/costumes/tuxedo/left_leg_trimmed.png"),
    "costumes/tuxedo/right_leg_trimmed.png": require("../assets/costumes/tuxedo/right_leg_trimmed.png"),
    "costumes/tuxedo/tie_trimmed.png": require("../assets/costumes/tuxedo/tie_trimmed.png"),
    "costumes/karate/body_trimmed.png": require("../assets/costumes/karate/body_trimmed.png"),
    "costumes/karate/left_hand_trimmed.png": require("../assets/costumes/karate/left_hand_trimmed.png"),
    "costumes/karate/right_hand_trimmed.png": require("../assets/costumes/karate/right_hand_trimmed.png"),
    "costumes/karate/left_leg_trimmed.png": require("../assets/costumes/karate/left_leg_trimmed.png"),
    "costumes/karate/right_leg_trimmed.png": require("../assets/costumes/karate/right_leg_trimmed.png"),
    "costumes/karate/head_band_trimmed.png": require("../assets/costumes/karate/head_band_trimmed.png"),
    "costumes/karate/green_head_band_trimmed.png": require("../assets/costumes/karate/green_head_band_trimmed.png"),
    "costumes/dancer/body_trimmed.png": require("../assets/costumes/dancer/body_trimmed.png"),
    "costumes/dancer/left_hand_trimmed.png": require("../assets/costumes/dancer/left_hand_trimmed.png"),
    "costumes/dancer/right_hand_trimmed.png": require("../assets/costumes/dancer/right_hand_trimmed.png"),
    "costumes/dancer/left_leg_trimmed.png": require("../assets/costumes/dancer/left_leg_trimmed.png"),
    "costumes/dancer/right_leg_trimmed.png": require("../assets/costumes/dancer/right_leg_trimmed.png"),
    "costumes/dancer/head_band_trimmed.png": require("../assets/costumes/dancer/head_band_trimmed.png"),
    "costumes/dancer/wand_trimmed.png": require("../assets/costumes/dancer/wand_trimmed.png"),
    "costumes/prisoner/body_trimmed.png": require("../assets/costumes/prisoner/body_trimmed.png"),
    "costumes/prisoner/left_hand_trimmed.png": require("../assets/costumes/prisoner/left_hand_trimmed.png"),
    "costumes/prisoner/right_hand_trimmed.png": require("../assets/costumes/prisoner/right_hand_trimmed.png"),
    "costumes/prisoner/left_leg_trimmed.png": require("../assets/costumes/prisoner/left_leg_trimmed.png"),
    "costumes/prisoner/right_leg_trimmed.png": require("../assets/costumes/prisoner/right_leg_trimmed.png"),
    "costumes/prisoner/hat_trimmed.png": require("../assets/costumes/prisoner/hat_trimmed.png"),
    "costumes/prisoner/weight_trimmed.png": require("../assets/costumes/prisoner/weight_trimmed.png"),
    "costumes/hockey/body_trimmed.png": require("../assets/costumes/hockey/body_trimmed.png"),
    "costumes/hockey/left_hand_trimmed.png": require("../assets/costumes/hockey/left_hand_trimmed.png"),
    "costumes/hockey/right_hand_trimmed.png": require("../assets/costumes/hockey/right_hand_trimmed.png"),
    "costumes/hockey/left_leg_trimmed.png": require("../assets/costumes/hockey/left_leg_trimmed.png"),
    "costumes/hockey/right_leg_trimmed.png": require("../assets/costumes/hockey/right_leg_trimmed.png"),
    "costumes/hockey/hat_trimmed.png": require("../assets/costumes/hockey/hat_trimmed.png"),
    "costumes/hockey/klushka_trimmed.png": require("../assets/costumes/hockey/klushka_trimmed.png"),
    "costumes/pioner/body_trimmed.png": require("../assets/costumes/pioner/body_trimmed.png"),
    "costumes/pioner/left_leg_trimmed.png": require("../assets/costumes/pioner/left_leg_trimmed.png"),
    "costumes/pioner/right_leg_trimmed.png": require("../assets/costumes/pioner/right_leg_trimmed.png"),
    "costumes/pioner/hat_trimmed.png": require("../assets/costumes/pioner/hat_trimmed.png"),
    "costumes/pioner/bluehat_trimmed.png": require("../assets/costumes/pioner/bluehat_trimmed.png"),
    "costumes/pioner/tie_trimmed.png": require("../assets/costumes/pioner/tie_trimmed.png"),
    "costumes/orange/body_trimmed.png": require("../assets/costumes/orange/body_trimmed.png"),
    "costumes/orange/hat_trimmed.png": require("../assets/costumes/orange/hat_trimmed.png"),
    "costumes/orange/weight_trimmed.png": require("../assets/costumes/orange/weight_trimmed.png"),
    "costumes/kgb/body_trimmed.png": require("../assets/costumes/kgb/body_trimmed.png"),
    "costumes/kgb/left_leg_trimmed.png": require("../assets/costumes/kgb/left_leg_trimmed.png"),
    "costumes/kgb/right_leg_trimmed.png": require("../assets/costumes/kgb/right_leg_trimmed.png"),
    "costumes/kgb/hat_front_trimmed.png": require("../assets/costumes/kgb/hat_front_trimmed.png"),
    "costumes/kgb/hat_back_trimmed.png": require("../assets/costumes/kgb/hat_back_trimmed.png"),
    "costumes/babushka/body_trimmed.png": require("../assets/costumes/babushka/body_trimmed.png"),
    "costumes/babushka/left_leg_trimmed.png": require("../assets/costumes/babushka/left_leg_trimmed.png"),
    "costumes/babushka/right_leg_trimmed.png": require("../assets/costumes/babushka/right_leg_trimmed.png"),
    "costumes/babushka/left_hand_trimmed.png": require("../assets/costumes/babushka/left_hand_trimmed.png"),
    "costumes/babushka/right_hand_trimmed.png": require("../assets/costumes/babushka/right_hand_trimmed.png"),
    "costumes/babushka/hat_trimmed.png": require("../assets/costumes/babushka/hat_trimmed.png"),
    "costumes/bear/body_trimmed.png": require("../assets/costumes/bear/body_trimmed.png"),
    "costumes/bear/bear_trimmed.png": require("../assets/costumes/bear/bear_trimmed.png"),
    "costumes/bear/right_hand_trimmed.png": require("../assets/costumes/bear/right_hand_trimmed.png"),
    "costumes/bear/hat_trimmed.png": require("../assets/costumes/bear/hat_trimmed.png"),
  },
  rocket: require("../assets/other/rocket_navalny_1000.png"),
  boot: require("../assets/other/boot.png"),
  menu: {
    ground: require("../assets/menu/menu_bg_ground.png"),
    sky: require("../assets/menu/menu_bg_sky1.png"),
    bunker: require("../assets/menu/menu_bg_bunker_w_shadow.png"),
    wheel: require("../assets/menu/menu_bg_wheel_alone.png"),
    grass: require("../assets/menu/menu_bg_grass_w_ground_w_shadow.png"),
    titleTop: require("../assets/menu/menu_bg_title_top.png"),
    titleBottom: require("../assets/menu/menu_bg_title_bottom.png"),
    titleTopRus: require("../assets/menu/menu_bg_title_top_rus1.png"),
    titleBottomRus: require("../assets/menu/menu_bg_title_bottom_rus1.png"),
    rocket: require("../assets/menu/rocket_300.png"),
    aliens: require("../assets/menu/alien_ship_300.png"),
    antennaLow: require("../assets/menu/antenna_low.png"),
    antennaHigh: require("../assets/menu/antenna_high.png"),
    buttons: {
      start: require("../assets/menu/start_button_00.png"),
      survival: require("../assets/menu/survival_button_00.png"),
      about: require("../assets/menu/about_button_00.png"),
      startRus: require("../assets/menu/start_button_rus1.png"),
      survivalRus: require("../assets/menu/survival_button_rus.png"),
      aboutRus: require("../assets/menu/about_button_rus1.png"),
    },
    rusFlag: require("../assets/menu/russian_flag.png"),
    engFlag: require("../assets/menu/american_flag.png"),
  },
  kickSound: require("../assets/sounds/kick.mp3"),
  hihatSound: require("../assets/sounds/hihat.mp3"),
  snareSound: require("../assets/sounds/snare.mp3"),
  rim1Sound: require("../assets/sounds/rim1.mp3"),
  rim2Sound: require("../assets/sounds/rim2.mp3"),
  menuSound: require("../assets/sounds/putin_menu1.mp3"),
  sounds: [
    require("../assets/sounds/putin_slova_0.mp3"),
    require("../assets/sounds/putin_slova_1.mp3"),
    //require("../assets/sounds/putin_slova_2.mp3"),
    //require("../assets/sounds/putin_slova_3.mp3"),
    require("../assets/sounds/putin_slova_4.mp3"),
    require("../assets/sounds/putin_slova_5.mp3"),
    require("../assets/sounds/putin_slova_6.mp3"),
    require("../assets/sounds/putin_slova_7.mp3"),
    require("../assets/sounds/putin_slova_8.mp3"),
    require("../assets/sounds/putin_slova_9.mp3"),
    require("../assets/sounds/putin_slova_10.mp3"),
    require("../assets/sounds/putin_slova_11.mp3"),
    require("../assets/sounds/putin_slova_12.mp3"),
    require("../assets/sounds/putin_slova_13.mp3"),
    require("../assets/sounds/putin_slova_14.mp3"),
    //require("../assets/sounds/putin_slova_15.mp3"),
    require("../assets/sounds/putin_slova_16.mp3"),
    require("../assets/sounds/putin_slova_17.mp3"),
    require("../assets/sounds/putin_slova_18.mp3"),
    require("../assets/sounds/putin_slova_19.mp3"),
  ],
  borderResources: {
    left: [
      require("../assets/map/map1_left_border_nofill_part1.png"),
      require("../assets/map/map1_left_border_nofill_part2.png"),
      require("../assets/map/map1_left_border_nofill_part3.png"),
      require("../assets/map/map1_left_border_nofill_part4.png"),
      require("../assets/map/map1_left_border_nofill_part5.png"),
      require("../assets/map/map1_left_border_nofill_part6.png"),
      require("../assets/map/map1_left_border_nofill_part7.png"),
      require("../assets/map/map1_left_border_nofill_part8.png"),
      require("../assets/map/map1_left_border_nofill_part9.png"),
      require("../assets/map/map1_left_border_nofill_part10.png"),
    ],
    right: [
      require("../assets/map/map1_right_border_nofill_part1.png"),
      require("../assets/map/map1_right_border_nofill_part2.png"),
      require("../assets/map/map1_right_border_nofill_part3.png"),
      require("../assets/map/map1_right_border_nofill_part4.png"),
      require("../assets/map/map1_right_border_nofill_part5.png"),
      require("../assets/map/map1_right_border_nofill_part6.png"),
      require("../assets/map/map1_right_border_nofill_part7.png"),
      require("../assets/map/map1_right_border_nofill_part8.png"),
      require("../assets/map/map1_right_border_nofill_part9.png"),
      require("../assets/map/map1_right_border_nofill_part10.png"),
    ],
  },
  tintedBorderResources: {
    left: [
      require("../assets/map/map1_left_border_wfill-01_part1.png"),
      require("../assets/map/map1_left_border_wfill-01_part2.png"),
      require("../assets/map/map1_left_border_wfill-01_part3.png"),
      require("../assets/map/map1_left_border_wfill-01_part4.png"),
      require("../assets/map/map1_left_border_wfill-01_part5.png"),
      require("../assets/map/map1_left_border_wfill-01_part6.png"),
      require("../assets/map/map1_left_border_wfill-01_part7.png"),
      require("../assets/map/map1_left_border_wfill-01_part8.png"),
      require("../assets/map/map1_left_border_wfill-01_part9.png"),
      require("../assets/map/map1_left_border_wfill-01_part10.png"),
    ],
    right: [
      require("../assets/map/map1_right_border_wfill-01_part1.png"),
      require("../assets/map/map1_right_border_wfill-01_part2.png"),
      require("../assets/map/map1_right_border_wfill-01_part3.png"),
      require("../assets/map/map1_right_border_wfill-01_part4.png"),
      require("../assets/map/map1_right_border_wfill-01_part5.png"),
      require("../assets/map/map1_right_border_wfill-01_part6.png"),
      require("../assets/map/map1_right_border_wfill-01_part7.png"),
      require("../assets/map/map1_right_border_wfill-01_part8.png"),
      require("../assets/map/map1_right_border_wfill-01_part9.png"),
      require("../assets/map/map1_right_border_wfill-01_part10.png"),
    ],
  },
  mapResources: [
    {
      bg: require("../assets/map/map1_bg_noblur_4x.png"),
    },
    {
      bg: require("../assets/map/map2_bg_noblur_4x.png"),
    },
    {
      bg: require("../assets/map/map3_bg_noblur_4x.png"),
    },
    {
      bg: require("../assets/map/map4_bg_noblur_4x.png"),
    },
    {
      bg: require("../assets/map/map5_bg_noblur_4x.png"),
    },
    {
      bg: require("../assets/map/map6_bg_noblur_4x.png"),
    },
  ],
  svgs: [
    chickenXml, // NOTE: chicken is an easter egg and should always be the first!!!!
    tuxedoXml,
    karateXml,
    dancerXml,
    hockeyXml,
    pionerXml,
    orangeXml,
    kgbXml,
    babushkaXml,
    bearXml,
  ],
};

export default Resources;
